__default__:
  account:       "eb-bb1271"
  partition:     "batch"
  ntasks:        1
  cpus-per-task: 16
  job-name:      "{rule}-%j"
  mail-type:     "ALL"
  mail-user:     "sr467@bath.ac.uk"
  output:        "{rule}-%j-%x.out"
  error:         "{rule}-%j-%x.err"
  time :         3

lammps:
  account: "eb-bb1271"
  time : 360

processAllLammps:
  time : 360

createGIF:
  time : 60

homer2H5:
  time : 15

plotHiC:
  time : 30
